### ISSUE TITLE
Extend DbParams validation to defined attribute checking

### ISSUE THREAD

**Issue by dvalters** [BritishGeologicalSurvey/etlhelper#1]
Make this a public method: https://github.com/BritishGeologicalSurvey/etlhelper/blob/e92bc4877e551e960eca9a03e0e6bf51555ae304/etlhelper/db_helper_factory.py#L53

These lines can go in a try-catch:

```python
try:
   helper = DB_HELPER_FACTORY.from_dbtype(db_type)
except DbHelperError as exc:
   raise DbParamsError
required_params = helper.required_parameters
```

**Comment by volcan01010** [comment]
Done in https://github.com/BritishGeologicalSurvey/etlhelper/releases/tag/v0.5.5
