### ISSUE TITLE
Fix commit_chunks in load() function

### ISSUE THREAD

**Issue by volcan01010** [BritishGeologicalSurvey/etlhelper#113]
### Description

The `commit_chunks` parameter that gets passed to `executemany` by the `load` function has been hard-coded to `True`.
If should be passed down from the `commit_chunks` variable as set in the function call.

https://github.com/BritishGeologicalSurvey/etlhelper/blob/2987d2a160c85c95b639c236a294a38c7c509c8b/etlhelper/etl.py#L404

```python
    executemany(query, conn, rows, commit_chunks=True)
```

### Acceptance criteria

+ [x] Call to `executemany` passes `commit_chunks=commit_chunks`
+ [x] Integration test demonstrates correct behaviour

**Comment by ximenesuk** [comment]
Closed manually. Tested via #115
