### ISSUE TITLE
Publish documentation online

### ISSUE THREAD

**Issue by volcan01010** [BritishGeologicalSurvey/etlhelper#12]
Current documentation is in README.md.  A Sphinx-based HTML page would make it easier to organise, search and read.  These pages should be automatically published online via CI.

Online location could be readthedocs or github.io pages.

+ [x] Documentation is moved from README.md to Sphinx-based pages
+ [x] CI pipeline publishes automatically on a new release

**Comment by volcan01010** [comment]
The `sqlite-utils` package has nice Sphinx-based docs that we could use as a guide.

https://github.com/simonw/sqlite-utils

https://sqlite-utils.datasette.io/en/stable/

**Comment by volcan01010** [comment]
Some text that could be part of documentation.

---

### ETL Helper has 3 components:

  + The **ETL functions**.  These take an open database connection and run queries against a database.  The functions simplify database interactions by handling cursors, allowing transformation of data, using memory-efficient iterators, handling errors and providing useful logging.  The connection can be created via ETLHelper or provided elsewhere e.g. from a connection pool.
  + The **Db Params** classes.  These hold the parameters required to select the correct driver and connect to a database and will helpfully tell you which are required.  They also have methods to write database connection strings for native and SQLAlchemy connections and to check whether a database is reachable.  They can also create database connections.
  + The **DbHelper** classes.  These work behind the scenes to smooth out differences between different database types and are not normally used directly. 

### Using ETL Helper simplifies workflows

Using native Python:

```python
# A Python script to transfer data from one database to another using native commands and cursors
# Notes should point out issues e.g. different driver names, cursors, holding data in memory, error handling
import sqlite3
import psycopg2

...
```

Using ETL Helper

```python
# A Python script doing the same using `copy_table_rows` and DbParams classes
# It can do a transform and print errors
from etlhelper import DbParams, copy_table_rows
from etlhelper.row_factories import dict_row_factory

...
```

For more customisation, lower-level ETL functions can be used 


```python
# A Python script doing the same using `iter_rows` and `executemany` and DbParams classes
# This can use custom SELECT queries and an INSERT query generated via `generate_insert_sql` and then modified.
from etlhelper import DbParams, copy_table_rows
from etlhelper.row_factories import dict_row_factory

db1 = DbParams(...)
db2 = DbParams(...)

with db1.connect() as src_conn:
    with db2.connect() as dest_conn:
        copy_table_rows('my_table', src_conn, dest_conn)
...
```

### ETLHelper 2.0 aim

ETL Helper 2.0 will add a database class that can create its own connections for an individual transaction and has the ETL functions as methods.
The ETL functions will be updated so that they can take a Database or a connection as the first argument.

```python
from etlhelper import Database

db1 = Database(...)
db2 = Database(...)

db1.copy_table_rows('my_table', db2)
```

**Comment by KoalaGeo** [comment]
https://github.com/BritishGeologicalSurvey/etlhelper/pull/112 ready to merge

**Comment by leorudczenko** [comment]
Docs work done by @KoalaGeo has been merged into the branch `for_v1`.
