### ISSUE TITLE
Document individual functions

### ISSUE THREAD

**Issue by rbroth** [BritishGeologicalSurvey/etlhelper#126]
It would be useful to have a list of functions and methods in library, aling with their arguments, what they return, and what they do. Similar to how methods are documented for e.g.[ node-oracledb](https://oracle.github.io/node-oracledb/doc/api.html#oracledbmethods)

**Comment by volcan01010** [comment]
Definitely.  Getting proper documentation has been on the TODO list for a while and is the main outstanding task before we go to v1.0.  It will make `etlhelper` much more accessible.

This is the original ticket: https://github.com/BritishGeologicalSurvey/etlhelper/issues/12

I'd hoped to get that done by Easter.  Now I hope to get it done this summer.  Seeing as you have expressed an interest, I may rope you in to help... ;)

**Comment by volcan01010** [comment]
The best description of the functions for now is in the source code itself.  The functions are defined here: https://github.com/BritishGeologicalSurvey/etlhelper/blob/main/etlhelper/etl.py

The plan is to use the Sphinx tool to autogenerate a webpage from those definitions and doc strings.
