### ISSUE TITLE
Create GitHub workflow for automated testing

### ISSUE THREAD

**Issue by leorudczenko** [BritishGeologicalSurvey/etlhelper#150]
### Summary

As an ETLHelper developer, I want to the tests for ETLHelper to automatically run in GitHub with a workflow and GitHub actions.

### Description

Currently, it can be awkward to run the tests locally as it requires database setup. This issue could be solved by creating an automated workflow using GitHub actions, which runs the tests remotely when a new change is made to ETLHelper.

A basic workflow which runs `pytest` can be found in the TACtool repository.
- The workflow files can be found [here](https://github.com/BritishGeologicalSurvey/tactool/tree/main/.github).
- The list of GitHub actions can be found [here](https://github.com/BritishGeologicalSurvey/tactool/actions).

The workflow should also run the tests in different versions of Python.
- An example of Python version testing in GitHub actions can be seen [here](https://github.com/BritishGeologicalSurvey/pygeoapi/blob/master/.github/workflows/main.yml).
- The docs for GitHub actions `matrix` can be found [here](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs).

### Acceptance Criteria

- [x] The repository includes a GitHub workflow for testing
- [x] The testing workflow is automatically run on a `push` if it modifies a `.py` file on any branch
- [x] The workflow runs the tests in multiple versions of Python (3.9, 3.10, 3.11)
- [x] Any old travis pipeline files are deleted
- [x] Any dummy Python files used to trigger the workflow are deleted before merging

**Comment by leorudczenko** [comment]
A GitHub workflow has been created for the repository, however, it is encountering an issue. Whenever the tests are run, an error occurs which states that the `sqlite3` module could not be found, despite the fact that it should be included with standard Python.

The workflow currently uses all 3 required Python versions, and the `sqlite3` module error is occurring on all of these versions.

**Comment by leorudczenko** [comment]
It has been decided to only run pytest in the GitHub workflow on the `test/unit` directory, as these tests run without causing import errors. This means that the current GitHub workflow achieves the same result as the previously used `.travis.yml` pipeline.

**Comment by volcan01010** [comment]
What happened to the `sqlite3` problem?  Did you fix it?
