### ISSUE TITLE
Add deprecation warning

### ISSUE THREAD

**Issue by rbroth** [BritishGeologicalSurvey/etlhelper#159]
Add a warning when module is imported that warns of various deprecation happening in version 1.0.0.

Warning should state that version 1.0.0 is coming soon and will contain deprecations.  Users should pin their versions and check GitHub issues for details.

**Comment by volcan01010** [comment]
Warning code can be triggered at top of __init__.py

https://github.com/BritishGeologicalSurvey/etlhelper/blob/main/etlhelper/__init__.py

**Comment by volcan01010** [comment]
https://docs.python.org/3/library/exceptions.html#DeprecationWarning
