### ISSUE TITLE
Add  "all" option for driver installation

### ISSUE THREAD

**Issue by rbroth** [BritishGeologicalSurvey/etlhelper#160]
When installing etlhelper with pip, the user needs to explicitly state the database drivers they want to install. If none are specified, none are installed. It would be good to add an option "all", which installs all drivers without having to specify each driver individually. This would also implicitly communicate that not providing  list of drivers will result in no drivers being installed.

**Comment by volcan01010** [comment]
Add an option for `all` here:

https://github.com/BritishGeologicalSurvey/etlhelper/blob/4615443a9c12459b56c2ceb8c6c3311d0af38bac/setup.py#LL59C1-L59C42

**Comment by ximenesuk** [comment]
> Add an option for `all` here:
> 
> https://github.com/BritishGeologicalSurvey/etlhelper/blob/4615443a9c12459b56c2ceb8c6c3311d0af38bac/setup.py#LL59C1-L59C42

This is in https://github.com/BritishGeologicalSurvey/etlhelper/pull/151/commits/c9c05a6df92f4162267a02b79ef61c12628b968a

**Comment by leorudczenko** [comment]
This has been completed on the `for_v1` branch.
