### ISSUE TITLE
Update docs and gh-pages workflow to run on `main`

### ISSUE THREAD

**Issue by KoalaGeo** [BritishGeologicalSurvey/etlhelper#161]
gh-pages currently runs on for_v1 branch, before going to tagged release v1.0 need to update .yml

There are other changes that we need to the docs, too:

+ [x] Update README to use `import etlhelper as etl` syntax
+ [x] Update .rst with latest README changes
+ [x] Add new introduction section describing three main components
+ [x] Update code section to only list docstrings for "public" modules
+ [ ] Add new logo (like the bottom of BGS logo, but with rock layers looking more like table rows)
+ [x] Link to v0.14.3 README to retain access to old documentation

**Comment by volcan01010** [comment]
For @leorudczenko 

+ [ ] Update autogenerated code docs so that they reflect what is available with `import etlhelper as etl`.  This may involve setting `__all__` attribute in the `__init__.py` file.

**Comment by volcan01010** [comment]
This was done in https://github.com/BritishGeologicalSurvey/etlhelper/pull/195/files
