### ISSUE TITLE
setup_oracle_client improvements

### ISSUE THREAD

**Issue by volcan01010** [BritishGeologicalSurvey/etlhelper#2]
### Summary

There are some improvements to `setup_oracle_client` that will make it more robust and useful.

### Details

The script is not covered by tests.  A unit test that installed from a dummy zip file could be created with minimal mocking.  It would demonstrate functionality.

The `data pump` provides similar functionality to `pgdump` for PostgreSQL and is provided by the instantclient tools.

Error `zipfile.BadZipFile` is thrown if the download was aborted and the partially installed file remains.  This is annoying.

### Acceptance criteria

* [x] ~~`--with-sqlplus` flag installs the SQL*Plus package and puts link into PATH~~ (let's keep this simple for now)
* [x] ~~`--with-tool` flag installs the instantclient tools package and puts link into PATH~~ (lets's keep this simple for now)
* [x] Unit test installs a dummy zip file into a temporary directory
* [x] ~~Pre-existing `oracle_lib_path_export` files on the PATH are removed~~ (use source instead)
* [x] ~~$VIRTUAL_ENV is used first to determine target location for `oracle_lib_path_export`~~ (use source instead)
* [x] `--log DEBUG` is replaced with `-v` flag
* [x] Logging format is cleaned up to replace `DEBUG:root:`
* [x] Corrupt, partially-downloaded zip files are automatically cleaned (cleanup before every install)
* [x] Can do just the environment setup part without having to download the client zip each time
* [x] `--reinstall` reinstalls packages, even if already correctly installed (e.g. to change instant client version)

**Comment by dvalters** [comment]
Traceback when trying to create a symlink when the file already exists:

````

Traceback (most recent call last):
  File "/home/decval/venvs/bgsetl_test/bin/setup_oracle_client_bgs", line 10, in <module>
    sys.exit(main())
  File "/home/decval/venvs/bgsetl_test/lib/python3.7/site-packages/bgs_etl/setup_oracle_client_bgs.py", line 30, in main
    setup_oracle_client(args.zip_location)
  File "/home/decval/dev/etlhelper/etlhelper/setup_oracle_client.py", line 50, in setup_oracle_client
    _create_path_export_script(instantclient_dir, script_dir)
  File "/home/decval/dev/etlhelper/etlhelper/setup_oracle_client.py", line 212, in _create_path_export_script
    os.symlink(script_file.absolute(), link_path)
FileExistsError: [Errno 17] File exists: '/home/decval/venvs/bgsetl_test/lib/python3.7/site-packages/bgs_etl/oracle_lib_path_export' -> '/home/decval/venvs/bgsetl_test/bin/oracle_lib_path_export'
```

Should probably fix to a nicer, non-Traceback error

**Comment by volcan01010** [comment]
Yes. And we should have a flag for doing just the environment setup part without having to download each time.  It wasn't such a problem with the BGS version when you didn't have to provide a valid path.

**Comment by volcan01010** [comment]
## Current version workflow

1) Check if all correctly configured (by test connect command to non-existent db) and return with message if so.
2) If not configured and no Linux, return with error message
3) Create install dir (and return path)
4) Install from zipfile (uses install dir and zip location, returns zipfile_path)
5) Create symlinks (uses zipfile_path, returns instantclient_dir)
6) Create path export script (uses instantclient_dir)

## Problems

+ [ ] can't run script without providing a download path
+ [ ] script fails badly if corrupt zip file found
+ [ ] symlink creation causes crash if one already exists

**Comment by volcan01010** [comment]
Required end state:

+ [ ] oracle_instantclient directory exists within `etlhelper` directory
+ [ ] zip file contents have been unpacked
+ [ ] symlinks between specific `libocci` and `libclntsh` versions and `.so` ending created
+ [ ] script to write the LD_LIBRARY_PATH export command exists
+ [ ] export command printing script is on $PATH

Questions:

+ what if using a different version of Instant Client?  Then the directory name changes.

**Comment by dvalters** [comment]
See also #44 perhaps

**Comment by volcan01010** [comment]
Information that the installation process requires:

+ if client is already configured
+ url for zip file download (optional)
+ zip file path (provided by user)
+ oracle_instantclient folder path
+ .so symlink locations (depends on version of instant client being installed)
+ directory containing setup script
+ oracle_lib_path_export script path (in directory above)
+ `bin` folder to make symlink
+ oracle_lib_path_export symlink (in directory above)

At the moment, this is collected at various stages

**Comment by dvalters** [comment]
![IMG_20200715_113322038_HDR](https://user-images.githubusercontent.com/10996571/87535976-3d0bdf80-c690-11ea-872f-3cadf8ab660e.jpg)

**Comment by dvalters** [comment]
## `SetterUpperClient` class
 - Contains attributes of all the information gathered above
 - Object knows which attrs are set and are valid. (i.e. is it a zipfile, downloaded etc)
 -

**Comment by volcan01010** [comment]
One other thing to check is whether we just need those two `.so` files.  If we don't need the rest then we can just copy those out from the zip, renaming as we go, then add the main directory to the LD_LIBRARY_PATH.

**Comment by volcan01010** [comment]
### Scenarios

| fcommand line params | client installed | outcome |
| ---- | ------ | ----|
| /path/to/file.zip | no | install client and print export message |
| http://file.zip | no | download zip, install client, print export message |
| - | no | print message, download oracle zip, install client, print export message |
| /path/to/file.zip | yes | print export message |
| http://file.zip | yes | print export message |
| - | yes | print export message |
| /path/to/file.zip --reinstall | yes | install client and print export message |
| http://file.zip --reinstall | yes | install client and print export message |
| --reinstall | yes | install client and print export message |

Note: http reference files are downloaded into install_dir.  File is not downloaded again unless called with reinstall.

**Comment by volcan01010** [comment]
Specification for `--reinstall` flag:

+ [ ] `--reinstall` flag added to argparse that uses "store_true" if called
+ [ ] setup_oracle_client takes reinstall as optional keyword argument (default=False)
+ [ ] `if reinstall`, then `_install_instantclient` function should be called, whatever `already_installed` is
+ [ ] unit test for calling `setup_oracle_client(dummy_zip, reinstall=True)`
+ [ ] unit test for calling `setup_oracle_client(dummy_zip, reinstall=False)`

The unit tests will need to use Pytest's `monkeypatch` and `unittest.mock.Mock` to mock out the following functions:
+ _oracle_client_is_configured (mock so return value is always False)
+ _check_install_status (mock so return value is always False)
+ _install_instantclient (so that tests can use `assert_called_once()` or `assert_not_called()`)

References:
+ https://docs.pytest.org/en/stable/monkeypatch.html#simple-example-monkeypatching-functions
+ https://docs.python.org/3/library/unittest.mock.html

**Comment by volcan01010** [comment]
It seems like the link to Oracle downloads is relatively official, as it is used in many places.  The main download page is at:

https://www.oracle.com/database/technologies/instant-client/linux-x86-64-downloads.html

We should mention the URL as a comment in the code.  We should also consider using the basiclite version by default as the file is much smaller.  I think the only difference is multilingual support.

https://download.oracle.com/otn_software/linux/instantclient/instantclient-basiclite-linuxx64.zip

**Comment by volcan01010** [comment]
More thoughts on the Instant Client installation:

+ If the default behaviour is to install from Oracle, then the argparse can be modified to make `--zip-location` a true optional parameter again.  The logic would be:

```python
if args.zip_location:
    zip_location = args.zip_location
else:
    zip_location = ORACLE_DEFAULT_ZIP_URL

...

setup_instant_client(zip_location)
```

+Logging outputs to stderr, print statements go to stdout.  We could write a file that contained `export LD_LIBRARY_PATH=/sdfdsf/sdfsd/sdfs:LD_LIBRARY_PATH` and the last step of the setup script could be to print the location.  That way, we could do the installation and path setup in one line: `source $(setup_oracle_client)`.

+ Going further, there are options for setting environment variables automatically for a given virtual environment.  See https://stackoverflow.com/a/52555465/3508733.  This is done by adding a `.pth` file that contains an `os.export` command to set the value.  It could be worth looking into this, but it might take a bit of experimentation.

+ Following from that reading, there are references to `site.py`.  In particular, `site.USER_BASE` could be used in `_get_working_directories` as a more "correct" way to find the locations.

+ If *that* all works, then it should be possible that `etlhelper` could install the Oracle client when you pip install it.  But people who aren't using Oracle wouldn't want that.  In this case, we could break out a separate package called `oracle-instantclient-linux` (unix?) and make it a dependency when you install `etlhelper[oracle]`.  That's all for another time...

**Comment by volcan01010** [comment]
I tried using a `.pth` file to modify the LD_LIBRARY_PATH whenever Python was called, but it didn't work.  The following code was called by `setup_oracle_client`:

```python

    # Add .pth file to site-packages to modify LD_LIBRARY_PATH dynamically
    # whenever Python is called.
    pth_file = Path(sysconfig.get_python_lib()) / "set_instantclient_ldlibrary_path.pth"
    content = dedent(f"""\
        # This file was created by etlhelper.setup_oracle_client.
        # It adds the Instant Client to the LD_LIBRARY_PATH whenever Python is run.
        # Linebreaks are escaped because commands should be one-liners.
        # In a virtualenv, the path entry is duplicated because site.addsitepackages()
        # gets called twice.
        import os; \
        old_path = os.getenv('LD_LIBRARY_PATH', ''); \
        client_dir = '{install_dir.absolute()}'; \
        os.environ['LD_LIBRARY_PATH'] = client_dir + ':' + old_path
        """).strip()
    pth_file.write_text(content)
```
This seemed to do as required.  This can be demonstrated in the Docker container used to run tests:

```
root@f47c851b4b75:/app# python -c "import os; print(os.environ)"
environ({'HOSTNAME': 'f47c851b4b75', 'PYTHON_VERSION': '3.6.9', 'PWD': '/app', 'HOME': '/root', 'LANG': 'C.UTF-8', 'APP': '/app', 'GPG_KEY': '0D96DF4D4110E5C43FBFB17F2D347EA6AA65421D', 'PYTHONPATH': '/app', 'TERM': 'xterm', 'SHLVL': '1', 'PYTHON_PIP_VERSION': '19.3.1', 'PYTHON_GET_PIP_SHA256': 'b86f36cc4345ae87bfd4f10ef6b2dbfa7a872fbff70608a1e43944d283fd0eee', 'PYTHON_GET_PIP_URL': 'https://github.com/pypa/get-pip/raw/ffe826207a010164265d9cc807978e3604d18ca0/get-pip.py', 'PATH': '/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin', '_': '/usr/local/bin/python', 'LD_LIBRARY_PATH': '/app/etlhelper/oracle_instantclient:'})
```

However, importing the Oracle libraries did not work.  Although this approach can modify the LD_LIBRARY_PATH, it seems that the modified version is not available to the system when it tries to run the Oracle libraries.

**Comment by volcan01010** [comment]
I've updated #49 to use `source $(setup_oracle_client)` syntax.
