### ISSUE TITLE
Fix typo in symlink to libclntsh.so

### ISSUE THREAD

**Issue by dvalters** [BritishGeologicalSurvey/etlhelper#26]
# Summary

There is a typo in this line when creating symlink names:

https://github.com/BritishGeologicalSurvey/etlhelper/blob/c664064cc2bd9382adb410fe3e966bc77128f22d/etlhelper/setup_oracle_client.py#L66

It should be **.so**

**Comment by volcan01010** [comment]
Closed by #31
