### ISSUE TITLE
Add fetch methods

### ISSUE THREAD

**Issue by volcan01010** [BritishGeologicalSurvey/etlhelper#29]
### Summary

Adding `fetchone` provides a convenient way to get a single row tuple.  Adding `fetchmany` and `fetchall` methods make the methods consistent with the DB API 2.0 cursor specifications.

### Description

There is currently no easy way to return a single row, equivalent to `cursor.fetchone` using the `etl` methods.  Instead, values need to be unpacked from a list, or calling `next` on `iter_rows` results.  Adding a `fetchone` function would make this nicer.  It would just use `iter_rows` and return the first value.

`fetchmany` could be modelled on the the `cursor.fetchmany` call signature and use `itertools.slice` to return the correct number of rows.  Whether or not to use named arguments and default values should be investigated.

`fetchall` would be synonymous with `get_rows`.

These new functions would be defined in the `etl` module.

### Acceptance criteria

+ [ ] New `fetchone` function returns single tuple
+ [ ] New `fetchmany` function returns list of tuples of specified length
+ [ ] New `fetchall` function returns list of all tuples
+ [ ] Integration tests are provided for at least PostgreSQL implementation

**Comment by metazool** [comment]
I like this suggestion, been doing a lot of catching StopIteration when i really intended to fetchone()
