### ISSUE TITLE
Help with pyinstaller

### ISSUE THREAD

**Issue by giuseppe-garzotto-treebyte** [BritishGeologicalSurvey/etlhelper#30]
Hello, 

I realize a simple program to create a SQLite database from an Oracle schema.
The script works very well and very fast.

Then, I tried to generate an exe file in order to quickly test the performance on different customers, e.g. without install python and all dependencies.

I used pyinstaller, with the following command line:

`pyinstaller --onefile --hidden-import=etlhelper.DBParams,etlhelper.connect,etlhelper.copy_rows,etlhelper.execute createdb.py
`
previously I tried:

`pyinstaller --onefile --hidden-import=etlhelper createdb.py`

The result is the same, when I execute the program from command line, I obtain:

```
Traceback (most recent call last):
  File "createdb.py", line 6, in <module>
    from etlhelper import DbParams
ModuleNotFoundError: No module named 'etlhelper'
[9504] Failed to execute script createdb
```

Probably I make some mistakes, but I can't understand where. Do you have any experience in using etlhelper with pyinstaller ?

Thanks in advice, and best regards and compliments for your work

Giuseppe Garzotto

**Comment by metazool** [comment]
I've not tried pyinstaller but this advice on module paths and hidden imports looks like your problem:
https://pythonhosted.org/PyInstaller/when-things-go-wrong.html#helping-pyinstaller-find-modules

**Comment by giuseppe-garzotto-treebyte** [comment]
First, thanks for the answer.

I see the link you suggest, and starting from it I found a number of other discussions about my problem.

A thing that I haven't mentioned in my previous message (sorry!) is that all the operations that I made are executed from a virtual environment created with **pipenv**.

And I think that **this** is the origin of the problem, because the execution of pyinstaller from a scratch intallation of Python, with all packages installed with pip and **without** virtual environments, exactly produce what I need: an exe that bundles all and that I can run on every computer without Python installed.

Actually, this is a solution I can accept. If I found a solution for executing pyinstaller inside a virtualenv I'll update this issue in order to provide support for other people.

**Comment by volcan01010** [comment]
Thanks.  Please re-open the issue or add another if you find anything helpful.

p.s. For information: the next version of `etlhelper` will contain breaking changes, so it is recommended to pin the version number that you use (currently 0.8.0)
