### ISSUE TITLE
Rename master to main

### ISSUE THREAD

**Issue by metazool** [BritishGeologicalSurvey/etlhelper#41]

**Comment by dvalters** [comment]
Done now, moved branch `master` to `main` with

`git branch -m master main`

Updated the default branch in settings.

Changed target branch of current pull requests to `main`.

There are some refernces to master in `versioneer.py` but I think these are from the versioneer code itself, or refer to other repos, so I left them in(?)

Probably just needs a once over check from @volcan01010 or someone to confirm

**Comment by dvalters** [comment]
Done now

**Comment by metazool** [comment]
<3
