### ISSUE TITLE
Improve Windows installation method and post-install check script

### ISSUE THREAD

**Issue by dvalters** [BritishGeologicalSurvey/etlhelper#44]
# Summary

Current `setup_oracle_client` could do more robust checking and helping post Oracle installation. (Compare with the logic for Linux OS i.e. setting paths and symlinks)

https://github.com/BritishGeologicalSurvey/etlhelper/blob/c721acbe0afbbe3ad4588666b59f8180f41774f5/etlhelper/setup_oracle_client.py#L148

**Comment by volcan01010** [comment]
Good call.  This is related to the refactoring in #2 (setup_oracle_client improvements), too.  We need to be able to check the client without passing a location for a zip file.  e.g.

```bash
setup_oracle_client
```

Either prints "success", or ld_client error, or if no sign of driver files, suggests that user runs command with the path/url to a zip file.

```bash
setup_oracle_client http:.../client.zip
```
Either prints "success" or ld_client error or if already installed, suggests that user runs command with `--force`

```bash
setup_oracle_client http://blah/client.zip --force
```
Wipes target directory for client files and installs again.
