### ISSUE TITLE
Consolidate MSSQL vs SQLServer

### ISSUE THREAD

**Issue by volcan01010** [BritishGeologicalSurvey/etlhelper#5]
## Summary

In some locations in the code Microsoft SQL Server is referred to as `mssql`, in others it is `sql_server`.  One of these should be chosen and used consistently to avoid confusion.

## Acceptance criteria

+ [ ] `sql_server` or `mssql` are used consistently throughout the code.

**Comment by volcan01010** [comment]
I think we should use `mssql` - this makes us consistent with SQLAlchemy: https://docs.sqlalchemy.org/en/13/dialects/mssql.html#module-sqlalchemy.dialects.mssql.pyodbc

**Comment by dvalters** [comment]
yeah I think that makes more sense, it's clearer that it's MS DB software
