### ISSUE TITLE
--reinstall option implementation notes

### ISSUE THREAD

**Issue by dvalters** [BritishGeologicalSurvey/etlhelper#54]
# Specification 

(from @jostev at  https://github.com/BritishGeologicalSurvey/etlhelper/issues/2#issuecomment-662694676 )

Specification for `--reinstall` flag:

This will need an `if (not) reinstall` before calling `_oracle_client_is_configured` and another before deciding to call `_install_instantclient`.

* [x]  `--reinstall` flag added to argparse that uses "store_true" if called
* [x]  setup_oracle_client takes reinstall as optional keyword argument (default=False)
* [x]  `if reinstall`, then `_install_instantclient` function should be called, whatever `already_installed` is
* [x]  unit test for calling `setup_oracle_client(dummy_zip, reinstall=True)`, assuming driver is not configured but is installed
* [x]  unit test for calling `setup_oracle_client(dummy_zip, reinstall=False)` assuming driver is not configured but is installed
* [x]  unit test for calling `setup_oracle_client(dummy_zip, reinstall=True)` assuming driver is configured

The unit tests will need to use Pytest's `monkeypatch` and `unittest.mock.Mock` to mock out the following functions:

* _oracle_client_is_configured (mock so return value is always False)
* _check_install_status (mock so we can control return value)
* _install_instantclient (so that tests can use `assert_called_once()` or `assert_not_called()`)

Example of mocking from elsewhere in `etlhelper`:

https://github.com/BritishGeologicalSurvey/etlhelper/blob/bd54a57d888049b6a4565f320e4839fa07d0ec4f/test/unit/test_db_helpers.py#L52

### References
 
 * https://docs.python.org/3/library/argparse.html#action (for store_true)
 * https://docs.pytest.org/en/stable/monkeypatch.html#simple-example-monkeypatching-functions
 * https://docs.python.org/3/library/unittest.mock.html

## Implementation notes

More detailed notes and ticket for the comment on the big issue at #2 

From the comment at https://github.com/BritishGeologicalSurvey/etlhelper/issues/2#issuecomment-662694676

https://github.com/BritishGeologicalSurvey/etlhelper/blob/feab09a1124cf9cdadb6c29518665084bbfb9855/etlhelper/setup_oracle_client.py#L24

Add a reinstall option == false argument.

https://github.com/BritishGeologicalSurvey/etlhelper/blob/feab09a1124cf9cdadb6c29518665084bbfb9855/etlhelper/setup_oracle_client.py#L34

Should reinstall if client configured, do not return here even if configured.

https://github.com/BritishGeologicalSurvey/etlhelper/blob/feab09a1124cf9cdadb6c29518665084bbfb9855/etlhelper/setup_oracle_client.py#L50

Needs modified so that it will override this behaviour and reinstall if asked for.

https://github.com/BritishGeologicalSurvey/etlhelper/blob/feab09a1124cf9cdadb6c29518665084bbfb9855/etlhelper/setup_oracle_client.py#L358

Add the argument here.

https://github.com/BritishGeologicalSurvey/etlhelper/blob/feab09a1124cf9cdadb6c29518665084bbfb9855/etlhelper/setup_oracle_client.py#L380

Pass `args.reinstall` here.

## To demo that it works

 - Whatever state of the installation we are at, make sure that install_instant client is called if reinstall is asked for. 

Add a test called `test_setup_oracle_client()`

https://github.com/BritishGeologicalSurvey/etlhelper/blob/feab09a1124cf9cdadb6c29518665084bbfb9855/etlhelper/setup_oracle_client.py#L34

Should be configured in the test to run with a Mock object that will return true or false as required.

https://github.com/BritishGeologicalSurvey/etlhelper/blob/feab09a1124cf9cdadb6c29518665084bbfb9855/etlhelper/setup_oracle_client.py#L46

Needs to be Mocked out so that we can control the return value.

https://github.com/BritishGeologicalSurvey/etlhelper/blob/feab09a1124cf9cdadb6c29518665084bbfb9855/etlhelper/setup_oracle_client.py#L51

Replace this with a MockInstallInstantClient so we can assert is has been called.

## Tests

test_has_been_installed_configured
test_has_been_installed_not_configured
 and vice versa with hasn't been installed. 

(2x2 matrix of options)

Example of mocking from elsewhere in `etlhelper`: https://github.com/BritishGeologicalSurvey/etlhelper/blob/bd54a57d888049b6a4565f320e4839fa07d0ec4f/test/unit/test_db_helpers.py#L52

**Comment by volcan01010** [comment]
This work was done in #55.
