### ISSUE TITLE
Further testing

### ISSUE THREAD

**Issue by dvalters** [BritishGeologicalSurvey/etlhelper#60]
## Summary

See coverage html.

 - [ ] Test on the zip location download (mock out download ziplfile, if zipfile location starts with http)
 - [x] Test on the args parse (can they be mocked?)
 - [ ] Test returns when oracle client is configured and not a reinstall (check log messages?)
 - [x] Check check install status when the install dir is empty.

**Comment by volcan01010** [comment]
Something like:

```python
# Arrange
mock_setup_oracle_client = Mock()
monkeypatch.setattr(soc, 'setup_oracle_client', mock_setup_oracle_client)
monkeypatch.setattr(sys, 'argv', ['http://some.url', '--reload', '-v'])

# Act (call main from setup_oracle_client module)
main()

# Assert
mock_setup_oracle_client.assert_called_with(...)
```

**Comment by volcan01010** [comment]
This work was completed in #55.
