### ISSUE TITLE
Investigate pyODBC fast_executemany option

### ISSUE THREAD

**Issue by volcan01010** [BritishGeologicalSurvey/etlhelper#86]
### Summary

We want to investigate the fast_executemany option for pyODBC cursors to see if it makes much difference and if it can be easily implemented.

### Description

The pyODBC driver includes an option for [fast_executemany](https://github.com/mkleehammer/pyodbc/wiki/Features-beyond-the-DB-API#fast_executemany).
It can be switched on by setting a flag on a cursor e.g. 

```python
cursor = conn.cursor()
cursor.fast_executemany = True
cursor.executemany(...)
```

We want to see if it makes a big difference, and if so, how it could be implemented.

Note that the `fast_executemany` flag is only recommended for Microsoft SQL Server ODBC driver and can modify behaviour of inserts.  Therefore it should be optional and off by default  (or should it?).

The implementation would involve either:
 - a custom `executemany` flag for `mssql` that takes an option, combined with a change in `etl.executemany` to accept and use the flag, and also in `etl.copy_rows`, or
 - a change in `db_helpers.mssql.py` to modify the way that cursors are created.  For example, the `db_helpers.sqlite.py` class has a custom `cursor` method.  The flag would need to be passed down from when the connection is created.

The first option would be simpler, but it would clutter the interface of the functions with options that are rarely used.

### Acceptance criteria

This ticket is just to investigate whether the flag is worth using.  The outputs is comments on this ticket that:

+ [x] compare executemany performance with and without the flag being switched on (using normal DBAPI commands)
+ [x] describe any other changes/differences that arise from using fast_executemany
+ [x] have high-level description of each implementation option (including example commands in each style) and discusses pros and cons of each in more detail
+ [x] discuss the pros/cons fixing it on (simpler implementation vs unexpected behaviour vs who are the users)

### References

+ Custom executemany for PostgreSQL: https://github.com/BritishGeologicalSurvey/etlhelper/blob/0fe626a2b1e268daeba4f351ebb8b4f9b34fdbf0/etlhelper/db_helpers/postgres.py#L50
+ Custom cursor for SQLite: https://github.com/BritishGeologicalSurvey/etlhelper/blob/0fe626a2b1e268daeba4f351ebb8b4f9b34fdbf0/etlhelper/db_helpers/sqlite.py#L48

**Comment by volcan01010** [comment]
Would storing the flag on the DbHelper instance for the MSSQL connection be a way of passing it round?  Does it persist in the right way?

**Comment by volcan01010** [comment]
If you can set the flag on the DbHelper class when creating the connection, the custom executemany could look like:

```python
def executemany(cursor, query, chunk):
    cursor.fast_executemany = self.fast_executemany
    cursor.executemany(query, chunk)
```

**Comment by ximenesuk** [comment]
I started to look at this from the angle of injecting in the flag, but as it is set on the cursor rather than the connection this isn't so straightforward without breaking changes. So after wasting some time on that I thought it would be better to look at potential performance by hard-coding a custom `executemany(...)` to test.

Setting `cursor.fast_executemany = True` immediately threw up this issue [Inserting into SQL server with fast_executemany results in MemoryError](https://github.com/mkleehammer/pyodbc/issues/547). A suggested solution of `cursor.setinputsizes([(pyodbc.SQL_WVARCHAR, 0, 0)])` didn't work for me. But changing the two `text` columns in the test table to ` varchar(max)` did allow the tests to complete successfully.

Given that this would be used against existing DBs where columns might be `(n)text` and the variability in support for this flag, I wonder if this is worth pursuing any further?

**Comment by ximenesuk** [comment]
I did run some hard-coded tests with the changed table definition and the test data increased to 100 rows. Each test was run six times, the range of times for `copy_rows` to complete is in seconds.
 -  `cursor.fast_executemany = True`: 925 - 5813
 -  `cursor.fast_executemany = True`: 18279 - 55714 (275972)

The exceptionally high value may be an outlier as I was having network issues - reflected in a very high time for `get_rows`, a better test would be from an internal VM or using a local SQL Server instance.

**Comment by volcan01010** [comment]
It's a pity that it isn't straightforward.  Did the hard-coded test results show a 10-20x speedup?  That's impressive.

I suppose that we should just put this to one side for now, then.  I've subscribed to the issue for updates.  We can come back to it again if it is resolved or if we have a project where loading to MS SQL Server is the bottleneck.

**Comment by ximenesuk** [comment]
Scratch the results above. Network issues! Same run today, more realistic. Getting rows was consistent between the two at about 135 s mean.

 - `cursor.fast_executemany = True`: 625 - 637   mean: 629
 - `cursor.fast_executemany = False`: 6987 - 7347  mean: 7130

**Comment by ximenesuk** [comment]
One solution for MS SQL is something like this:

```
    def executemany(self, cursor, query, chunk):
        """
        Try to  executemany for SQL Server.

        :param cursor: Open database cursor.
        :param query: str, SQL query
        :param chunk: list, Rows of parameters.
        """

        try:
            cursor.fast_executemany = True
            cursor.executemany(query, chunk)
        except MemoryError:
            cursor.fast_executemany = False
            cursor.executemany(query, chunk)
```

There seems to be little overhead in getting the exception.

**Comment by volcan01010** [comment]
That's a nice solution.  You could also raise a warnings.warn to explain that you'd fallen back to the `fast_executemany = False`.

It would be nice for users to be able to switch `fast_executemany` off if it had other unwanted side effects.  The `connect` function is part of the base `DbHelper` class and can take any number of `kwargs`.  We could override the `MSSQLDbHelper.connect` function so that it could store a flag e.g.

```python
    def connect(self, db_params, password_variable=None, use_fast_executemany=True, **kwargs):
        self.use_fast_executemany = use_fast_executemany
        return super().connect(self., db_params, password_variable)
```

The method above then becomes:

```
    def executemany(self, cursor, query, chunk):
        """
        Try to  executemany for SQL Server.

        :param cursor: Open database cursor.
        :param query: str, SQL query
        :param chunk: list, Rows of parameters.
        """

        try:
            cursor.fast_executemany = self.use_fast_executemany
            cursor.executemany(query, chunk)
        except MemoryError:
            warn('Message about fast_executemany failed, falling back to default implementation (link for info?)')
            cursor.fast_executemany = False
            cursor.executemany(query, chunk)
```

This requires the same DbHelper object to be used to get the connection as to call the executemany.  In theory, we only ever need need one DbHelper object, so we could modify the HelperFactory to ensure that is the case (functools.lru_cache on the `from_dbtype` function). 
https://github.com/BritishGeologicalSurvey/etlhelper/blob/5f1f1780589f5d4a8136dff223f95e7854512c6b/etlhelper/db_helper_factory.py#L54
