### ISSUE TITLE
Allow custom error handling for executemany (and execute?)

### ISSUE THREAD

**Issue by volcan01010** [BritishGeologicalSurvey/etlhelper#91]
### Summary

As an etl process writer, I would like to customise what happens when executemany encounters an error so that I can ignore errors if required.

### Details

The current behaviour of `executemany` is to raise an `ETLHelperInsertError` if there is a problem inserting data (e.g. failed foreign key constraint).  This aborts the whole process.  In this situation, the `commit_chunks` flag determines whether the whole process is rolled back, or if chunks that have already been transferred are preserved.

Sometimes is it useful to just log an error and continue.  Other times, users may want to do something else (e.g. update a database table with failure information).  For maximum flexibility, we could allow users to pass through a function to be called when executemany raises an error.

https://github.com/BritishGeologicalSurvey/etlhelper/blob/5f1f1780589f5d4a8136dff223f95e7854512c6b/etlhelper/etl.py#L262

`etlhelper` could provide two built-in options.  The first replicates the current behaviour.  The second allows the process to continue.

```python
def log_and_raise(chunk, exc, logger):
    msg = (f"Failed to insert chunk: [{chunk[0]}, ..., {chunk[-1]}]\n"
                f"SQL query raised an error.\n\n{query}\n\n"
                f"Required paramstyle: {helper.paramstyle}\n\n{exc}\n")
    logger.debug(msg)
    raise ETLHelperInsertError(msg)
```

```python
def log_and_continue(chunk, exc, logger):
    msg = (f"Failed to insert chunk: [{chunk[0]}, ..., {chunk[-1]}]\n"
                f"SQL query raised an error.\n\n{query}\n\n"
                f"Required paramstyle: {helper.paramstyle}\n\n{exc}\n")
    logger.error(msg)
```

### Acceptance criteria

+ `executemany` has an `on_error` argument that takes a function of `chunk`, `exc`, `logger` that is called when an error is encountered
+ `copy_rows` also takes an `on_error` flag and passes it through to `executemany`
+ `log_and_raise` and `log_and_continue` are defined in `etlhelper.exceptions`
+ default option is `log_and_raise`
+ tests in `test.integration.etl.test_etl_load` cover each error handling function in `executemany`
+ tests in `test.integration.etl.test_etl_transform` cover each error handling function in `copy_rows`

**Comment by ximenesuk** [comment]
There are some initial commits in https://github.com/BritishGeologicalSurvey/etlhelper/tree/handle-load-error

The test for `log_and_continue` highlights the problem here (it currently outputs the list of ids in the table written to). The failures are at a chunk level, if one row fails all rows subsequent are not inserted, and so any continue needs to pick up the missed rows.

Are there any arguments that can be passed to the upstream helper functions to handle this?

If not then `log_and_continue` would need to invoke (or flag) running `execute` over the failed batch or re-chunking  using progressively smaller sizes - i.e. recursive!

**Comment by ximenesuk** [comment]
I've added a branch https://github.com/BritishGeologicalSurvey/etlhelper/tree/recursive-many which is illustrative but handles chunks containing duplicate rows recursively. This solves the problem but is fairly ugly. It would need to handle other exceptions caused by problem rows, so may need to use `IntegrityError` and `DataError` more generally. I have not confirmed whether the count `processed` is correct.

**Comment by volcan01010** [comment]
It's complicated.  I'd been thinking about it for a while and am glad to have your opinion, too.  I think that going through the data row-by-row is unavoidable in some settings.

New thoughts from today are:

I can think of four different scenarios that we need to address:

+ User just wants to fail quickly on the first error in the chunk (current behaviour)
+ User wants to retry row-by-row and only fail on the problem row, so that they can get full data
+ User wants to retry row-by-row and log the problem rows, so that they can get a list of them
+ User wants to retry row-by-row and call a custom function on problem rows e.g. so they can write them to a file or post them to some queue

If we have an ErrorHandler class, it could have an error function that gets called e.g.

```python
class BaseErrorHandler:
    handler_function = None

    def __init__(self, sql, chunk, exc, logger, ...):
        self.sql = sql
        self.chunk = chunk
        ...

    def handle_error_rows(self):
        for row in chunk:
            try:
                execute(self.sql, self.row, ...)
            except:
                self.handler_function(row, exc, logger, ...)

class LogAndContinueErrorHandler(BaseErrorHandler):
    handler_function = log_and_continue

class CustomErrorHandler(BaseErrorHandler):
    handler_function = my_error_function
```

I'm not sure how much that helps, but it may reduce repetition of code between different handler functions.  
If we wanted to get really recursive, we could make `chunksize` a parameter of `executemany` and then call it again with `chunksize=1` to retry the rows.

In the `executemany` code we could do:

```python
try:
    helper.executemany(...)
except helper.Exceptions as exc:
    if on_error_handler is None:
        # Current behaviour - no handler specified
        raise
    else:
        handler = on_error_handler(sql, chunk, exc, logger, ...)
        handler.handle_error_rows()
```

**Comment by volcan01010** [comment]
I had a simpler idea. Either we fail on the first error, as now,  or we have a `catch_failures` option that retries the individual rows and then returns the failed one with their exceptions at the end. Users can do what they want with them afterwards.

The benefit is simplicity, the downside is that the list of failed data could get very big.

**Comment by volcan01010** [comment]
I've been thinking even more!  I think that the best compromise will be:

```python
try:
    # call executemany on the chunk
except:
    # Roll back failed executemany
    conn.rollback()

    if on_error:  # If we have been given a function to call
        # Retry the chunk one row at a time, capturing a list of failed rows and their errors
        bad_rows_and_errors = execute_by_row()
        on_error(bad_rows_and_errors)
    else:
        # Raise the error from the failed executemany
        raise
```

The `execute_by_row` will be something like:

```python
def execute_by_row(sql, conn, chunk, helper):
    bad_rows_and_errors = []

    for params in chunk:
        try:  
            execute(sql, conn, params)
        except helper.exception as exc:
            conn.rollback()
            bad_rows_and_errors.append((params, exc))
```

The benefits of this are:

- It's simple, with no need for handler classes
- `on_error` function gets called once per chunk, so there is less risk of overloading memory
- `on_error` function gets called once per chunk, so there can be feedback along the way
- `bad_rows_and_errors` is a list of tuples that will be easy for users to define functions to work with
- Users don't have to worry about handling exceptions

Example `on_error` functions could be as simple as:

```python
# Collect all the errors to deal with at the end
errors = []
executemany(sql, conn, on_error=errors.extend)


# Log the errors to the etlhelper logger
from etlhelper import logger

def log_errors(bad_rows_and_errors):
    for row, error in bad_rows_and_errors,
        logger.error(error)

executemany(sql, conn, on_error=log_errors)

# Write the failed ids to a file
def write_bad_ids(bad_rows_and_errors):
    with open('bad_ids.txt', 'at') as out_file:
        for row, error in bad_rows_and_errors,
            out_file.write(f"{row.id}\n")

executemany(sql, conn, on_error=write_bad_ids)
```
